name: build_container_image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: 5ttr8c9rf9
          context: .
          push: true
          tags: "trelent/opentextembeddings:${{ github.sha }} , trelent/opentextembeddings:latest"
          token: ${{ secrets.DEPOT_TOKEN }}
