name: build_container_image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04=
    steps:
      - uses: actions/checkout@v3
      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: 5ttr8c9rf9
          context: .
          push: true
          tags: "opentextembeddings/opentextembeddings:${{ github.sha }}"
          token: ${{ secrets.DEPOT_TOKEN }}
